version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123321
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123321
      ME_CONFIG_MONGODB_URL: mongodb://root:123321@mongodb:27017/
