version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: six-cities-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123321
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123321
      ME_CONFIG_MONGODB_URL: mongodb://admin:123321@mongodb:27017/
