#Add comment
POST http://localhost:4000/comment/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZha2VfMTFAZmFrZS5jb20iLCJ1c2VySWQiOiI2MzVhYzMxMGU5MGQ1YzEyZjhhMGJjZTgiLCJpYXQiOjE2NjY4OTI2MjEsImV4cCI6MTY2NzA2NTQyMX0.rsLGUYSMFjlBC-Oj6hYNQ6gKboWb5un1Rw0Q5X2bViY

{
  "offerId": "635ac9204b061d6586a88c2d",
  "text": "commment text 3 lakjsdlkjcpxovopxcvi",
  "rating": 5
}
###

#Get comments list
GET http://localhost:4000/comment/list/635ac9204b061d6586a88c2d HTTP/1.1
Content-Type: application/json

{
  "offerId": "635ac9204b061d6586a88c2d",
  "text": "commment text 3 lakjsdlkjcpxovopxcvi",
  "rating": 5
}
###
